# Generated by Django 5.0.6 on 2024-05-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0002_industria_avatar_alter_empresa_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industria',
            name='avatar',
        ),
        migrations.AddField(
            model_name='pais',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
