# Generated by Django 5.0.6 on 2024-05-31 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0003_remove_industria_avatar_pais_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
    ]
