# Generated by Django 5.0.6 on 2024-05-31 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0004_alter_empresa_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'Sector', 'verbose_name_plural': 'Sectores'},
        ),
    ]
